version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-graphql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: cmos
      MYSQL_DATABASE: graphql_auth
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
